version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: go test -coverprofile=c.out -race -covermode=atomic
      - codecov/upload:
          file: c.out
